version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  db:
    driver: bridge
